version: "3.8"

networks:
  backend:
    driver: bridge

services:
  app:
    container_name: pipo
    build: .
    restart: unless-stopped
    env_file: .env
    networks:
      - backend
    deploy:
      resources:
        reservations:
          memory: 250M
        limits:
          memory: 400M
