version: "3.8"

networks:
  backend:
    driver: bridge

services:
  app:
    container_name: pipo
    build: .
    env_file: .env
    networks:
      - backend
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 3
        condition: on-failure
      resources:
        reservations:
          memory: 250M
        limits:
          memory: 400M
