version: "3.8"

networks:
  backend:
    driver: bridge

services:
  app:
    container_name: pipo
    build: .
    restart: unless-stopped
    environment:
      SERVICE_NAME: pipo
    env_file:
      - .env
    networks:
      - backend
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        tag: httpd.access
        env: SERVICE_NAME
    depends_on:
      - fluentd

  fluentd:
    container_name: fluentd
    image: fluent/fluent-bit:2.1.4
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent-bit.conf
      - ./fluentd_parsers.conf:/fluentd/etc/parsers.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
