version: "3.8"

networks:
  backend:
    driver: bridge

services:
  app:
    container_name: pipo
    build: .
    restart: unless-stopped
    environment:
      SERVICE_NAME: pipo
    env_file:
      - .env
    networks:
      - backend
