dynaconf_merge: true
default:
  # Remote Queue
  player:
    queue:
      broker:
        url:
        host:
        port:
        vhost:
  # Discord API token
  token:
  # Spotify client id + secret
  spotify_client:
  spotify_secret: