default:
  log:
    level: INFO
    encoding: utf-8
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  # Application name
  app:
  # Discord channel
  channel:
  # Discord default voice channel
  voice_channel:
  server_id: "@format {this.CHANNEL}"
  bot_description: Discord Music Bot
  commands:
    prefix: "-"
    # ensure same values are used in help messages
    search: -q
    shuffle: -s
  pipo:
    move_message_delay: 0.2       # seconds
    check_if_playing_frequency: 3 # seconds
    on_exit_disconnect_timeout: 5 # seconds
    ffmpeg_config:
      options: "-vn"
      before_options: "-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5"
  player:
    task_name: play_music_queue
    messages:
      disconnect: Bye bye !!!
      play_error: Unable to play next music. Skipping.
      unavailable_status: Status unavailable for used queue type.
    idle:
      task_name: idle_tracker
      timeout: 1800  # 30 minutes
    queue:
      type: local
      default: local
      local:
        get_music:
          retries: 3
          block: true
          timeout: 8
        prefetch_limit: 10
      remote:
        url:
        host:
        port:
        vhost:
        max_consumers: 10
        requests:
          max: 100
          timeout: 43200      # seconds
        timeout:
          broker: 60 # seconds
          broker_graceful: 120 # seconds
          get_op: 30          # seconds
          consume: 30         # seconds
        size_check_iterations: 3
        queues:
          dispatcher:
            queue: dispatcher
            args:
              message-ttl: 3600000 # 1 hour
          transmuter:
            exchange: providers
            routing_key: "provider."
            youtube:
              queue: youtube
              routing_key: "@format {this.PLAYER__QUEUE__REMOTE__QUEUES__TRANSMUTER__ROUTING_KEY}youtube.default"
              args:
                message-ttl: 43200000 # 12 hours
            youtube_query:
              queue: youtube_query
              routing_key: "@format {this.PLAYER__QUEUE__REMOTE__QUEUES__TRANSMUTER__ROUTING_KEY}youtube.query"
              args:
                message-ttl: 3600000 # 1 hour
            spotify:
              queue: spotify
              routing_key: "@format {this.PLAYER__QUEUE__REMOTE__QUEUES__TRANSMUTER__ROUTING_KEY}spotify.*"
              args:
                message-ttl: 3600000 # 1 hour
          hub:
            base_queue: "hub-queue-"
            queue: "@format hub-queue-{this.SERVER_ID}"
            base_routing_key: "hub."
            routing_key: "@format hub.{this.SERVER_ID}"
            exchange: processed_music
            args:
              message-ttl: 43200000 # 12 hours
              x-expires: 86400000   # 24 hours
    url_fetch:
      lock_timeout: 3 # seconds
      timeout: 600    # seconds
      pool_size: 2
      retries: 3
      wait: 1
    source:
      youtube:
        downloader_config: # YoutubeDL music download method args
          format: bestaudio/best
      spotify:
        playlist:
          limit: 50
          filter: "items.track.name,items.track.artists.name"
        album:
          limit: 50     # max allowed by Spotify API
test:
  dynaconf_merge: true
  log:
    level: DEBUG
  server_id: "TEST"
