default:
  log_level: INFO
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(data)s"
  # Application name
  app:
  # Discord channel
  channel:
  # Discord default voice channel
  voice_channel:
  bot_description: Discord Music Bot
  commands:
    prefix: "-"
    # ensure same values are used in help messages
    search: -q
    shuffle: -s
  pipo:
    move_message_delay: 0.5 # seconds
    check_if_playing_frequency: 3 # seconds
  player:
    messages:
      play_error: Unable to play next music. Skipping.
      disconnect: Bye bye !!!
    idle_timeout: 1800  # 30 minutes
    queue:
      type: local
      default: local
      local:
        size_check_iterations: 5
    url_fetch:
      timeout: 300 # seconds
      max_cache_size: 64
      pool_size: 16
      retries: 3
      wait: 1
