default:
  log_level: INFO
  # Application name
  app:
  # Discord channel
  channel:
  # Discord default voice channel
  voice_channel:
  command:
    commands:
      prefix: "-"
      # ensure same values are used in help messages
      search: -q
      shuffle: -s
  pipo:
    move_message_delay: 0 # seconds
    check_if_playing_frequency: 3 # seconds
  player:
    messages:
      play_error: Unable to play next music. Skipping.
      disconnect: Bye bye !!!
    idle_timeout: 1800  # 30 minutes
    queue:
      local:
        size_check_iterations: 5
    url_fetch:
      timeout: 300 # seconds
      max_cache_size: 64
      pool_size: 16
      retries: 3
      wait: 1
