default:
  log_level: DEBUG
  # Application name
  app:
  # Discord channel
  channel:
  # Discord default voice channel
  voice_channel:
  command:
    commands:
      prefix: "-"
      shuffle: s
  player:
    messages:
      play_error: Unable to play next music. Skipping.
      disconnect: Bye bye !!!
    idle_timeout: 1800  # 30 minutes
    queue:
      local:
        size_check_iterations: 5
    url_fetch:
      timeout: 3
      max_cache_size: 128
      pool_size: 4
      retries: 3
      wait: 1
