default:
  # Application name
  app:
  # Discord channel
  channel:
  # Discord default voice channel
  voice_channel:
  command:
    queue:
      max_workers: 2
    commands:
      shuffle: s
  player:
    idle_timeout: 1800  # 30 minutes
    queue:
      size_check_iterations: 5
    url_fetch:
      max_cache_size: 128
      pool_size: 4
      retries: 3
      wait: 1
