# This workflow will
# - build docker image with arm7 as target (as used by Raspberry Pi 4 Model B);
# - push image to a repository.
# For more information see:
# https://github.com/docker/setup-buildx-action
# https://github.com/marketplace/actions/build-and-push-docker-images

name: Build/Publish Docker Image

on:
  workflow_run:
    workflows: [ "Test Application" ]
    types:
      - completed
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "main" ]

jobs:
  docker:
    name: Build + Publish Docker Image
    runs-on: ubuntu-22.04
    env:
      PUBLISH: ${{ github.event_name != 'pull_request' && github.event.workflow_run.conclusion == 'success'}}
      REGISTRY: docker.io
      TARGET_PLATFORMS: linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Git Version
      id: version
      uses: codacy/git-version@2.8.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: Set variables
      if: success()
      id: prepare
      shell: bash
      run: |
        echo image=${GITHUB_REPOSITORY@L} >> $GITHUB_OUTPUT
        echo platforms=${TARGET_PLATFORMS} >> $GITHUB_OUTPUT

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ steps.prepare.outputs.image }}
          ghcr.io/${{ steps.prepare.outputs.image }}
        tags: |
          type=sha

    - name: Login to Docker Hub registry
      if: ${{ env.PUBLISH }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_CI_USERNAME }}
        password: ${{ secrets.DOCKER_CI_ACCESS_TOKEN }}

    - name: Login to Github Container registry
      if: ${{ env.PUBLISH }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        sbom: true
        push: ${{ env.PUBLISH }}
        build-args: |
          PROGRAM_VERSION=${{ steps.version.outputs.version }}
        tags: |
          ${{ steps.version.outputs.version }}
          ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ steps.prepare.outputs.platforms }}

    - name: Update Docker Hub description
      if: ${{ env.PUBLISH }}
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_CI_USERNAME }}
        password: ${{ secrets.DOCKER_CI_ACCESS_TOKEN }}
        repository: ${{ steps.prepare.outputs.image }}
