# This workflow will
# - build the docker image with arm7 as target (as used by Raspberry Pi 4 Model B);
# - push the image to a repository.
# For more information see:
# https://github.com/docker/setup-buildx-action
# https://github.com/marketplace/actions/build-and-push-docker-images

name: Build + Publish Docker Images

on:
  workflow_run:
    workflows: [ "Test Application" ]
    types:
      - completed
  push: # TODO add other branches later if required, like dev
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    name: Build + Publish Docker Images
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: TODO
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${DOCKER_TARGET_PLATFORM}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
    - name: Set variables
      if: success()
      id: prepare
      shell: bash
      run: |
        export DOCKER_IMAGE=${GITHUB_REPOSITORY,,}
        echo docker_platform=${DOCKER_TARGET_PLATFORM} >> $GITHUB_OUTPUT
        echo docker_image=${DOCKER_REGISTRY}/${DOCKER_IMAGE} >> $GITHUB_OUTPUT
        echo version=${GITHUB_RUN_NUMBER} >> $GITHUB_OUTPUT
        echo tag=${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${GITHUB_RUN_NUMBER} >> $GITHUB_OUTPUT
    - name: Test build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: ${{ steps.prepare.outputs.tag }}
        platforms: ${{ steps.prepare.outputs.docker_platform }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push (new release)
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.prepare.outputs.tag }}
        platforms: ${{ steps.prepare.outputs.docker_platform }}
    - name: Build and push (latest)
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.prepare.outputs.docker_image }}:latest
        platforms: ${{ steps.prepare.outputs.docker_platform }}
