# This workflow will
# - ensure branch dependencies is up to date in accordance to dev.

name: Rebase 'dependencies' branch

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

jobs:
  rebase:
    name: Rebase 'dependencies' with 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, one would need to push refs to dest repo
          ref: dependencies
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase -Xours origin/dev
          git push origin dependencies --force
